---
- name: install build dependencies
  command: "yum-builddep -y {{ sandbox.git_repository }}/beaker.spec"

- name: install EPEL
  package:
    name: epel-release
    state: present

- name: install runtime dependencies
  package:
    name:
        - python-gunicorn
        - nodejs-less
        - syslinux-tftpboot
        - libvirt-client
        - firefox # for tests
        - openldap-servers
        - python-gunicorn
        - python-gssapi
        - python-qpid-proton
        - python-mock
        - python-pwquality
        - python-isodate
        - python-kerberos
        - python-lockfile
        - python-nose-progressive
        - python-rdflib
        - python-requests-kerberos
        - python-tgexpandingformwidget
        - selenium-python
        - uglify-js
        - xorg-x11-server-Xvfb
        - pylint
        - xz  # to import database dumps
        - rhts-devel # to build task RPMs
        - beakerlib
    state: present

- name: install auxiliary tools
  package:
    state: present
    name:
        - git
        - python-virtualenv
        - pytest
        - python-sphinx

- name: Install SIG Cloud OpenStack
  package:
    name: centos-release-openstack-train
    state: present

- name: install OpenStack packages
  package:
    state: present
    name:
        - python-keystoneclient
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
