---
- name: install build dependencies
  command: "yum-builddep -y {{ sandbox.git_repository }}/beaker.spec"

- name: install EPEL
  package:
    name: epel-release
    state: present

- name: install runtime dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-gunicorn
    - nodejs-less
    - syslinux-tftpboot
    - cobbler
    - libvirt-client
    - firefox # for tests
    - openldap-servers
    - python-gunicorn
    - python-isodate
    - python-kerberos
    - python-lockfile
    - python-nose-progressive
    - python-rdflib
    - python-requests-kerberos
    - python-tgexpandingformwidget
    - selenium-python
    - uglify-js
    - xorg-x11-server-Xvfb
    - pylint
    - PyXML  # needed by beah and used on Jenkins in dogfood tests
    - xz  # to import database dumps
    - rhts-devel # to build task RPMs
    - beakerlib

- name: install auxiliary tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python-virtualenv
    - pytest
    - python-sphinx

- name: install Juno OpenStack package repository
  copy:
    src: centos-openstack-juno.repo
    dest: /etc/yum.repos.d/centos-openstack-juno.repo
    owner: root
    group: root
    mode: 0644

- name: copy CentOS Cloud SIG key
  copy:
    src: CentOS-Cloud-SIG-key.asc
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Cloud
    owner: root
    group: root
    mode: 0600

- name: import CentOS Cloud SIG key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Cloud

- name: install Juno OpenStack packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-keystoneclient
    - python-glanceclient
    - python-novaclient
    - python-neutronclient
