---
- name: install build dependencies
  command: "yum-builddep -y {{ sandbox.git_repository }}/beaker.spec"

- name: install EPEL
  package:
    name: epel-release
    state: present

- name: install runtime dependencies
  package:
    name:
        - python-gunicorn
        - nodejs-less
        - syslinux-tftpboot
        - libvirt-client
        - bzip2 # firefox dep
        - gtk3 # firefox dep
        - libXt # firefox dep
        - openldap-servers
        - python-gunicorn
        - python-gssapi
        - python-qpid-proton
        - python-mock
        - python-pwquality
        - python-isodate
        - python-kerberos
        - python-lockfile
        - python-nose-progressive
        - python-rdflib
        - python-requests-kerberos
        - python-tgexpandingformwidget
        - selenium-python
        - uglify-js
        - xorg-x11-server-Xvfb
        - pylint
        - xz  # to import database dumps
        - rhts-devel # to build task RPMs
        - beakerlib
    state: present

- name: install auxiliary tools
  package:
    state: present
    name:
        - git
        - python-virtualenv
        - pytest
        - python-sphinx

- name: Install SIG Cloud OpenStack
  package:
    name: centos-release-openstack-train
    state: present

- name: install OpenStack packages
  package:
    state: present
    name:
        - python-keystoneclient
        - python-glanceclient
        - python-novaclient
        - python-neutronclient

- name: Download Firefox 52 # For selenium compatibility
  get_url:
    url: https://ftp.mozilla.org/pub/firefox/releases/52.7.0esr/linux-x86_64/en-US/firefox-52.7.0esr.tar.bz2
    dest: /firefox-52.7.0esr.tar.bz2

- name: Remove firefox package
  package:
    name: firefox
    state: absent

- name: Create Firefox directory
  file:
    path: /opt/firefox-52.7.0esr
    state: directory
    mode: 0755

- name: Unpack Firefox
  unarchive:
    src: /firefox-52.7.0esr.tar.bz2
    dest: /opt/firefox-52.7.0esr
    remote_src: true
    creates: /opt/firefox-52.7.0esr/firefox/firefox

- name: Create symlink for Firefox
  file:
    src: /opt/firefox-52.7.0esr/firefox/firefox
    dest: /usr/bin/firefox
    state: link
