# This playbook sets the MariaDB SQL server.
---

- name: set SCL MariaDB facts on Redhat/CentOS systems
  set_fact:
    mysql_service: "rh-mariadb102-mariadb"
    is_scl_server: true
    my_cnf_location: "/etc/opt/rh/rh-mariadb102/my.cnf"
  when: ansible_distribution in ("RedHat", "CentOS")

- name: set MariaDB facts on Fedora systems
  set_fact:
    mysql_service: "mariadb"
    is_scl_server: false
    my_cnf_location: "/etc/my.cnf"
  when: ansible_distribution == "Fedora"

- name: install mariadb-server package
  package:
    name: mariadb-server
    state: present
  when: not is_scl_server

- name: install SCL
  package:
    name: centos-release-scl
    state: present
  when: is_scl_server

- name: enable SCL repository
  command: yum-config-manager --enable rhel-server-rhscl-7-rpms
  when: is_scl_server

- name: install SCL RH-MariaDB 10.2 package
  package:
    name: rh-mariadb102
    state: present
  when: is_scl_server

- name: install system-wide wrapper for RH-MariaDB
  package:
    name: rh-mariadb102-mariadb-syspaths
    state: present
  when: is_scl_server

- name: copy MariaDB config
  copy:
    src: my.cnf
    dest: "{{ my_cnf_location }}"
    owner: root
    mode: 0600
    backup: yes

- name: Create the directory /etc/mysql/conf.d
  file:
    path: /etc/mysql/conf.d
    state: directory

- name: start sql service and enable the service
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: create the beaker database
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ databases }}"

- name: create beaker user
  mysql_user:
    name: "{{ item[0].name }}"
    password: "{{ item[0].password }}"
    priv: "{{ item[1] }}.*:ALL,GRANT"
    append_privs: yes
    state: present
  with_nested:
    - "{{ users }}"
    - "{{ databases }}"

- name: initialize beaker database
  command: beaker-init -u {{ beaker_server_admin_user }} -p {{ beaker_server_admin_pass }} -e {{ beaker_server_email }}
  when: beaker_server_admin_user is defined

