---
- name: check storage volumes
  virt_pool:
    command: facts

- name: show storage volumes
  debug:
    var: ansible_libvirt_pools

- name: create storage volumes
  command: "virsh vol-create-as {{ storage_pool_name }} {{ item.name }} {{ item.capacity }} --allocation {{ item.allocation }}"
  failed_when: "configure_result.rc != 0 or 'exists already' in configure_result.stderr"
  with_items: "{{ libvirt_volumes }}"
  register: configure_result
  when: "item.name not in ansible_libvirt_pools[storage_pool_name].volumes"

- name: Define test systems
  virt:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'domain.xml.j2') }}"
  with_items: "{{ network.hosts[1:] }}"

- name: Enable test systems
  virt:
    name: "{{ item.name }}"
    state: shutdown
  with_items: "{{ network.hosts[1:] }}"
